// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dayuebhcfhocbnhbgikn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRheXVlYmhjZmhvY2JuaGJnaWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MTc5MjIsImV4cCI6MjA1OTk5MzkyMn0.pYAE2Fuvsr2huK2AqLRk_x-IhwbjHTXtuCKbZVWODbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);